### ISSUE TITLE
Is there a reason why this is not available on npm ?

### ISSUE THREAD

**Issue by detj** [ProjectMoon/flux#11]
Is the reason technical in nature or not ?

**Comment by ProjectMoon** [comment]
A few years ago, Facebook asked me if they could use the name, since I hadn't updated the package in the ~2 years before that. I said sure. Took the package out of npm, [they got the name](https://www.npmjs.com/package/flux), and I haven't bothered to put it back into npm under another name (much less update it for newer versions of node).
